### ISSUE TITLE
When run through the console (python -m rira), it gives an error:

### ISSUE THREAD

**Issue by WestonDrop** [apratimshukla6/RiRa#6]
I did everything according to the instructions

(RiRa-main-ln0KUbM-) C:\Users\dropw\Desktop\RiRa-main>python -m rira
Traceback (most recent call last):
  File "d:\python  3.8.6\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\python  3.8.6\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dropw\Desktop\RiRa-main\rira\__main__.py", line 1, in <module>
    from . import bot
  File "C:\Users\dropw\Desktop\RiRa-main\rira\bot.py", line 10, in <module>
    bot = commands.Bot(command_prefix=cfg["$"], activity=discord.Activity(type=discord.ActivityType.listening, name="!help ❤️"), help_command=None)
TypeError: 'NoneType' object is not subscriptable

**Comment by grantwforsythe** [comment]
1. What were your exact steps? Did you simply clone the repo, update `config.yml`, and run the bot?
2. Did you install the required 3rd party libraries?

Aside: Your comment isn't very descriptive so it makes it harder for people to try and help you. It's always best to provide as much relevant information as possible and to be specific.
